# Generated by Django 2.2.28 on 2023-11-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=3)),
                ('item_name', models.CharField(max_length=15)),
                ('item_desc', models.CharField(max_length=100)),
                ('item_price', models.FloatField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='media/Product-images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category', '-created')},
        ),
    ]
