# Generated by Django 2.2.28 on 2023-11-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20231116_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Rest_id',
            field=models.CharField(default=3, max_length=3),
            preserve_default=False,
        ),
    ]
