# Generated by Django 2.2.28 on 2023-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_auto_20231116_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link_id',
            field=models.CharField(default=4, max_length=3),
            preserve_default=False,
        ),
    ]
