# Generated by Django 2.2.28 on 2023-11-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_auto_20231117_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Product', to_field='Rest_id'),
        ),
    ]
